

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-fastapi_db}
      - JWT_SECRET=${JWT_SECRET:-cambiarsecreto}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app-network
    command: uvicorn app.main:myapp --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-fastapi_db}
    ports:
      - "5435:5432"
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge