"""seeder

Revision ID: 400b4fc40c5f
Revises: 4f1379a2c7b2
Create Date: 2025-11-03 22:12:37.172149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from typing import Optional

try:
    # prefer using the app's password hasher if available
    from app.core.security import get_password_hash
except Exception:
    # fallback: simple no-op hasher (not ideal but ensures migration runs)
    def get_password_hash(pw: str) -> str:
        return pw


# revision identifiers, used by Alembic.
revision: str = '400b4fc40c5f'
down_revision: Union[str, None] = '4f1379a2c7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    admin_email = "admin@example.com"
    admin_full_name = "Admin"
    admin_password = "admin"  # change after first run in production
    admin_role = "ADMIN"

    # check if admin user already exists (idempotent)
    sel = sa.text("SELECT id FROM users WHERE email = :email")
    res = conn.execute(sel, {"email": admin_email})
    row = res.scalar()
    if row is None:
        # create hashed password
        try:
            pwd_hash = get_password_hash(admin_password)
        except Exception:
            pwd_hash = admin_password

        ins = sa.text(
            "INSERT INTO users (email, full_name, password_hash, role) VALUES (:email, :full_name, :password_hash, :role)"
        )
        conn.execute(ins, {
            "email": admin_email,
            "full_name": admin_full_name,
            "password_hash": pwd_hash,
            "role": admin_role,
        })
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    admin_email = "admin@example.com"
    del_stmt = sa.text("DELETE FROM users WHERE email = :email")
    conn.execute(del_stmt, {"email": admin_email})
    # ### end Alembic commands ###
