"""add_owner_id_to_tags

Revision ID: 4f1379a2c7b2
Revises: 822e5e1b8e02
Create Date: 2025-11-01 16:48:07.112627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1379a2c7b2'
down_revision: Union[str, None] = '822e5e1b8e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tags', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'owner_id')
    # ### end Alembic commands ###
